#debug: true

server:
  port: 8081
#Embedded active MQ
#ActiveMQ supports multiple protocols to connect to the message broker. In this example, we will be using OpenWire protocol.
spring:
  activemq:
    broker-url: tcp://localhost:61616
    password: admin
    user: admin

#below mail configuration is required along with email-service jar
  mail:
    host: smtp.gmail.com
    port: 587
    username: lekh700 #from lekh700@gmail.com Less secure app access must be on in this gmail account
    password: lekh_700 #gmail pass

    properties:
      mail:
        debug: true
        transport:
          protocol: smtp
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true